#!/bin/sh

pgrep -x mate-settings-daemon > /dev/null || mate-settings-daemon &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x guake > /dev/null || guake &
pgrep -x blueman-applet > /dev/null || blueman-applet &
#pgrep -x mate-power-manager > /dev/null || mate-power-manager &
pgrep -x nm-applet > /dev/null || nm-applet &

wmname LG3D &
#vmware-user-suid-wrapper &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#30302f'
bspc config presel_feedback_color '#512da8'

feh --bg-fill ~/Wallpapers/archkali.png &
~/.config/polybar/./launch.sh --shapes &

picom --config ~/.config/picom/picom.conf &
# wal -R
eww daemon
eww open neofetch
eww open shortcuts
sleep 3
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x blueman-applet > /dev/null || blueman-applet &
bspc rule -a Kupfer.py focus=on
sleep 1
bspc rule -a Plank layer=above manage=off border=off
pgrep -x plank > /dev/null || plank
#bspc rule -a Conky manage=off
#pgrep -f conky-startup.sh > /dev/null || /home/visvasrk/.conky/conky-startup.sh &
